### ISSUE TITLE
.idea packed into npm package

### ISSUE THREAD

**Issue by cdrani** [ilicmarko/devtools-timeline-images#2]
`.idea` folder is included in your npm package. Ideally the package should be as light as possible, and in this case only include the necessary files like index.js, readme, license, and package.json. 

Fix is to add a __fields__ key to package.json with the files you want to include in the package. license, readme, and package.json are  included by default.

```json
"files": ["index.js"]
```

**Comment by ilicmarko** [comment]
I was thinking of removing the `.idea` folder all together but I can use files or even better `.npmignore`.

Will add.

**Comment by cdrani** [comment]
I think the files field is a better option than .npmignore in this case. Otherwise you'll have to include everything you included in the .gitignore file in the .npmignore file as well.
