### ISSUE TITLE
shorter name for command?

### ISSUE THREAD

**Issue by cdrani** [ilicmarko/devtools-timeline-images#3]
Not an issue per se, but how about a shorter command name or at least an alias to a shorter command ? Perhaps an acronym of the package name `dti`? If a user's terminal has autocomplete then it wouldn't really be a problem, but it's just an idea.

**Comment by ilicmarko** [comment]
I don't think is a great idea to take up multiple command names as you can overlap with other projects. For example `dti` is already used multiple times:
https://www.npmjs.com/package/dti-cli
https://www.npmjs.com/package/dti

If someone finds the command long (which I also do) the best solution is to add an alias.

**Comment by cdrani** [comment]
Ok. That's understandable.
